# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20180822_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
