# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_auto_20180823_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
