# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180822_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
