# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvote',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
