from django.conf.urls import url, include
from .views import *

urlpatterns = [
    url(r'^$', issues_list, name='all_open_issues'),
    url(r'^(?P<page>\d+)/$', issues_list, name='open_issues_paged'),
    url(r'^closed/$', 
    issues_list, {'open_issues': False}, name='all_closed_issues'),
    url(r'^closed/(?P<page>\d+)/$', 
        issues_list, {'open_issues': False}, name='closed_issues_paged'),
    url(r'^bugs/$', issues_list, {'issue_type': 'BG'}, name='all_open_bugs'),
    url(r'^bugs/(?P<page>\d+)/$', 
        issues_list, {'issue_type': 'BG'}, name='open_bugs_paged'),
    url(r'^bugs/closed/$', 
        issues_list, {'issue_type': 'BG', 'open_issues': False}, name='all_closed_bugs'),
    url(r'^bugs/closed/(?P<page>\d+)/$', 
        issues_list, {'issue_type': 'BG', 'open_issues': False}, name='closed_bugs_paged'),
    url(r'^requests/$', 
        issues_list, {'issue_type': 'FR'}, name='all_open_requests'),
    url(r'^requests/(?P<page>\d+)/$', 
        issues_list, {'issue_type': 'FR'}, name='open_requests_paged'),
    url(r'^requests/closed/$', 
        issues_list, {'issue_type': 'FR', 'open_issues': False}, name='all_closed_requests'),
    url(r'^requests/closed/(?P<page>\d+)/$', 
        issues_list, {'issue_type': 'FR', 'open_issues': False}, name='closed_requests_paged'),
    url(r'^(?P<id>\d+)/view/$', issue_detail, name='view_issue'),
    url(r'^create/$', issue_create, name='create_issue'),
    url(r'^status/(?P<status>[a-z-]+)/$', 
        issues_list, name='all_issues_by_status'),
    url(r'^status/(?P<status>[a-z-]+)/(?P<page>\d+)/$', 
        issues_list, name='issues_by_status_paged'),
    url(r'^category/(?P<category>\d+)/$', 
        issues_list, name='all_issues_by_category'),
    url(r'^category/(?P<category>\d+)/(?P<page>\d+)/$', 
        issues_list, name='issues_by_category_paged'),
]